# Generated by Django 4.2.6 on 2023-10-18 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0002_remove_employee_name_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='name_reference',
            field=models.ManyToManyField(to='reference.reference', verbose_name='Справка'),
        ),
    ]
