# Generated by Django 4.2.6 on 2023-10-18 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0003_employee_name_reference'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['full_name'], 'verbose_name': 'Сотрудника', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.RemoveField(
            model_name='employee',
            name='name_reference',
        ),
    ]
