# Generated by Django 4.2.6 on 2023-10-18 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0004_alter_employee_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='full_name',
            field=models.CharField(max_length=100, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.BooleanField(choices=[(True, 'Работает'), (False, 'Уволен')], default=True, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='referenceemployee',
            name='date_start',
            field=models.DateField(verbose_name='Дата получения справки'),
        ),
        migrations.AlterField(
            model_name='referenceemployee',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reference.employee', verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='referenceemployee',
            name='status',
            field=models.BooleanField(choices=[(True, 'Активна'), (False, 'Просрочена')], default=True, verbose_name='Статус справки'),
        ),
    ]
