# Generated by Django 4.2.6 on 2023-10-18 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0005_alter_employee_full_name_alter_employee_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referenceemployee',
            name='status',
        ),
    ]
