# Generated by Django 4.2.6 on 2023-10-19 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0008_alter_employee_date_of_birth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='referenceemployee',
            old_name='employee',
            new_name='employee_name',
        ),
        migrations.AddField(
            model_name='employee',
            name='reference_list',
            field=models.ManyToManyField(to='reference.referenceemployee'),
        ),
    ]
