# Generated by Django 4.2.6 on 2023-10-19 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0010_alter_employee_reference_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='referenceemployee',
            old_name='employee_name',
            new_name='employee',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='reference_list',
        ),
    ]
