# Generated by Django 4.2.6 on 2023-10-23 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0011_rename_employee_name_referenceemployee_employee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='company_name',
        ),
        migrations.AddField(
            model_name='employee',
            name='company_name',
            field=models.ManyToManyField(to='reference.company', verbose_name='Компания'),
        ),
    ]
